### ISSUE TITLE
coc-utils is not valid coc extension error message  

### ISSUE THREAD

**Issue by ogfunkycold** [GideonWolfe/vim.reaper#10]
Installing vim.reaper for first time as indicated in readme.md I've got the following error:

coc-utils   coc-utils is not valid coc extension, "engines" fiekd with coc property required.

I'm using endeavor 2020-09 iso and aur/neovim-git 0.4.0.r2116.geee0668818-1 (+210 3.01) (Installed: 0.4.0.r2684.ga1ed941a7-1)

**Comment by Ziad0dev** [comment]
I am having the same issue any fix for this.

**Comment by Ziad0dev** [comment]
https://github.com/coc-extensions/coc-utils/commit/c17e9b8f4b1be5e7d8ea029d109143213dfb430c

**Comment by GideonWolfe** [comment]
fixed by #11

**Comment by Antonio-Bennett** [comment]
Hi Gideon,

I am actually experiencing this same error. I am trying to install coc-utils from the marketplace and am on a windows machine. Please let me know if you need any details, I'm pretty fresh at vim.
![image](https://user-images.githubusercontent.com/31296212/105627940-cf432c00-5e07-11eb-80f2-e93f260ff83b.png)

**Comment by Antonio-Bennett** [comment]
> fixed by #11
Hi Gideon,

I am actually experiencing this same error. I am trying to install coc-utils from the marketplace and am on a windows machine. Please let me know if you need any details, I'm pretty fresh at vim.
![image](https://user-images.githubusercontent.com/31296212/105627999-2943f180-5e08-11eb-9cf2-5c83efe3831a.png)

**Comment by GideonWolfe** [comment]
I don't think this is even a coc extension anymore, I removed it from the config.

**Comment by Antonio-Bennett** [comment]
Is there any alternative because a function suggested on the official COC repo for selecting pop up Windows uses the float function in Utils I think

**Comment by Bad3r** [comment]
This issue still occures in the latest version

**Comment by Bad3r** [comment]
To supress this error. Edit
```bash
$HOME/.config/nvim/configs/plugin-settings.vim
```
and delete the line `314` containing `\'coc-utils'`
```lua
      \'coc-template',
      \'coc-utils'
      \]
```
make sure to remove the trailing comma `,` at the end of line `313` ` \'coc-template',`
```lua
      \'coc-template'
      \]
```
