### ISSUE TITLE
Fresh install errors (coc)

### ISSUE THREAD

**Issue by ThatOneCalculator** [GideonWolfe/vim.reaper#14]
SCROLL TO BOTTOM, UPDATE

**Comment by ThatOneCalculator** [comment]
After running `:PlugInstall`, I now get this:

```
[coc.nvim] Unable to load global extension at /home/kainoa/.config/coc/extensions/node_modules/coc-ccls: main file ./lib/extension.js not found, you may need to build the proj
ect.
Press ENTER or type command to continue
```

**Comment by ThatOneCalculator** [comment]
I also get this after hitting enter:
![image](https://user-images.githubusercontent.com/44733677/125547848-525c4d82-4cfe-42eb-9543-f9df2a57d3e3.png)

**Comment by ThatOneCalculator** [comment]
The 1 error I'm stuck on after some debugging:
```
[coc.nvim] Unable to load global extension at /home/kainoa/.config/coc/extensions/node_modules/coc-ccls: main file ./lib/extension.js not found, you may need to build the proj
ect.
Press ENTER or type command to continue
```

**Comment by GideonWolfe** [comment]
Hey there! I think you're running into [this](https://github.com/Maxattax97/coc-ccls/issues/2#issuecomment-604324630) issue. I linked directly to the fix.

**Comment by ThatOneCalculator** [comment]
~~This fixed that! Now I get ***another*** error: `minimap: this plugin requires code-minimap to be installed.`~~

A quick `yay -S code-minimap` fixed that too. No more errors!

**Comment by GideonWolfe** [comment]
Glad to hear it :smile:

**Comment by ThatOneCalculator** [comment]
@GideonWolfe I actually have one more question, how can I remove that kinda smooth scrolling effect?

**Comment by GideonWolfe** [comment]
It's the smooth scroll plugin, you can just comment it out in your plugins file and it will be disabled
