### ISSUE TITLE
ccls error

### ISSUE THREAD

**Issue by Ziad0dev** [GideonWolfe/vim.reaper#16]
if you get this error [coc.nvim] Unable to load global extension at /home/xxx/.config/coc/extensions/node_modules/coc-ccls: main file ./lib/extension.js not found, you may need to build the project.
the npm package is broken the fix is:
``cd ~/.config/coc/extensions/node_modules/coc-ccls
``
``
ln -s node_modules/ws/lib lib
``

**Comment by GideonWolfe** [comment]
Thanks for writing this up in case someone searches here for the solution! I always forget about this until I have to do my setup on another machine

**Comment by Ziad0dev** [comment]
yeah same switched to nixOS and totally forgot about it
