### ISSUE TITLE
JDK not being detected

### ISSUE THREAD

**Issue by luxploit-old** [GideonWolfe/vim.reaper#2]
i have installed openjdk 13 & 10 and everytime i open nvim it says:

`The java.home variable defined in settings point to a missing folder, Get The Java Development Kit?`

`1. Yes`
`2. No`

how do i fix this? Also this is a fresh install of Arch that i'm running

**Comment by luxploit-old** [comment]
I've fix it. in .config/nvim/coc-settings.json, change this Line:

From: `"java.home": "/usr/lib/jvm/java-12-openjdk"`

To: `"java.home": "/usr/lib/jvm/java-13-openjdk"`

`java-13-openjdk` can be changed to`java-8-openjdk` ,if you don't have the latest java version

**Comment by GideonWolfe** [comment]
Yep, you just have to edit that line based on whatever directory you have JDK installed. I believe CoC can use any JDK version >= 8
