### ISSUE TITLE
Disable java-coc

### ISSUE THREAD

**Issue by apertureless** [GideonWolfe/vim.reaper#3]
Hi, 
I always getting an error if I start vim

```
The java.home variable defined in settings does not point to a JDK., Get the Java Development Kit?:
1. Yes
2. No
```

However, I do not really need any java support, thus I don't want to install the java jdk.

I've tried following:

- Remove `coc-java` from [plugin-settings.vim](https://github.com/GideonWolfe/vim.reaper/blob/master/nvim/configs/plugin-settings.vim#L275)
- Uninstall `coc-java` plugin `:CocList extensions` -> Uninstall
- Remove `java.home` from `coc-settings.json`

But, the message still appears and always want input.
What am I missing?

**Comment by GideonWolfe** [comment]
That's very strange behavior, thanks for submitting an issue.

All the methods you tried *should* have worked. 
Removing `coc-java` from `plugins-settings.vim` would prevent the plugin from being autoinstalled, but would not remove it if it was previously installed.

I would try a few of the built in CoC commands to try and fix it.
`CocUninstall coc-java`
`CocRebuild`

And make sure the entire line in `coc-settings.json` is removed.

If that doesn't work, I would suspect it's a CoC problem.

**Comment by apertureless** [comment]
Yeah, it's driving me crazy, because I can't figure out, where the message comes from.

It seems that it gets generated by the `coc-java` [package](https://github.com/neoclide/coc-java/blob/master/src/requirements.ts)

However, it should not be present in my system anymore.

I've ran

- `CocUninstall coc-java`
- `CocRebuilt`
- `CocRestart`

Also deleted the `.config/coc/extensions` before, so it's a clean install.

But the message still appears.

**Comment by GideonWolfe** [comment]
Hmm yes I would suggest opening this issue on the coc-java or coc page, they would probably have a better idea of what's wrong. If it turns out to be a misconfiguration here, let me know and I'll fix it

**Comment by X1Zeth2X** [comment]
Having similar issues aswell. Hope this gets fixed.

**Comment by apertureless** [comment]
Solution is to also remove the `coc-xml` extension, as it requires java, too.
