### ISSUE TITLE
Markdown Preview not working

### ISSUE THREAD

**Issue by bowl00** [GideonWolfe/vim.reaper#4]
I am attempting to use the new MarkdownPreview command with the updated configs and it is not working. I set a custom browser to point to vivaldi-stable and I also attempted installing firefox and setting that as the browser. Am I missing a requirement for this to work? I can't find much information when it comes to requirements for this plugin.
Using arch linux with i3

**Comment by GideonWolfe** [comment]
What exactly isn't working? Does the preview appear at all?

The markdown preview plugin requires an an absolute filepath to the custom `css`, so make sure to replace "gideon" with your username in `plugin-settings.vim`, or disable the custom look altogether.

Of course to get it to work you need to run `:PlugInstall` to actually download the markdown preview plugin, but I'm assuming you did that already.

I'm also using arch with i3, and this plugin required virtually no setup to get working. I didn't even set it to open Firefox, it just did it by default.

The only thing I can think of is my port choice of `3456` might conflict with another service you have running? You can try disabling that to check.

**Comment by bowl00** [comment]
I actually got it to work by replacing this line:
```
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
```

With this line:
```
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
```

Thank you for the response! Not sure what is causing the original line to not work for me.

**Comment by GideonWolfe** [comment]
Interesting, that first line is pulled straight from the markdown-preview documentation! Glad you have it working!
