### ISSUE TITLE
Consider adding fzf  

### ISSUE THREAD

**Issue by mseidl** [GideonWolfe/vim.reaper#5]
One of the plugins requires fzf, so you should just include it in the default config...

**Comment by GideonWolfe** [comment]
I'm not quite sure how to do this... `fzf` is a regular system package. I downloaded it on arch with `yay fzf`. Here are [commands](https://github.com/junegunn/fzf#using-linux-package-managers) for other package managers.

The `fzf` vim plugin is not required for vim.reapers functionality, and I don't currently use it, hence why it isn't included.

Feel free to make a case why you think the fzf vim plugin provides more features than just having `fzf` installed.

**Comment by mseidl** [comment]
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

They mention this on the fzf github thing.

**Comment by GideonWolfe** [comment]
I'll think about it... The `fzf` package is extremely popular and available in pretty much every repo. 

Not sure why I would tie an system wide package that the user may or may not want with the default set of plugins. It should be managed with a package manager.

Are there certain features from the `fzf.vim` plugin that you want to see in vim.reaper? I'm trying to keep the plugins list short/sane, so I feel like there would have to be a good benefit from what you can already do.

**Comment by mseidl** [comment]
It's ok. but it's not in the main opensuse repos.
