### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by atidyshirt** [GideonWolfe/vim.reaper#6]
Some airline symbols are missing and being replaced with this symbol (⍰), I'm probably just missing something, any help would be appreciated. I am using Mac OS and missing images are as shown below. 

Thanks, Jordan.

![Screen Shot 2020-02-11 at 10 45 06 AM](https://user-images.githubusercontent.com/20514752/74193096-a93a7f80-4cbb-11ea-8289-544244468c4c.png)

**Comment by GideonWolfe** [comment]
Hey Jordan, thanks for opening the issue.

Usually when symbols don't show up, it's a limitation of the terminal emulator in which neovim is running. Try pasting various unicode symbols in the terminal, you will probably see similar boxes.

You can look into changing the settings [here](https://github.com/GideonWolfe/vim.reaper/blob/7fff1daff79c21af104cffb04ec82579b28ea7bf/nvim/configs/plugin-settings.vim#L93), where you can put custom symbols you know your terminal will render.

You could also try disabling unicode [here](https://github.com/GideonWolfe/vim.reaper/blob/7fff1daff79c21af104cffb04ec82579b28ea7bf/nvim/configs/plugin-settings.vim#L123) or powerline fonts [here](https://github.com/GideonWolfe/vim.reaper/blob/7fff1daff79c21af104cffb04ec82579b28ea7bf/nvim/configs/plugin-settings.vim#L95).

Great looking setup by the way!

**Comment by atidyshirt** [comment]
Thanks for such a quick reply, I will try to isolate the problem with symbols if not I can import custom symbols. Do you think the symbols will show with Linux? if so I have another system that I will try to replicate this setup with. Cheers for comments on setup :)

**Comment by GideonWolfe** [comment]
The symbols will definitely show on Linux. I'm using Arch Linux with URxvt, and I have powerline fonts installed.

**Comment by atidyshirt** [comment]
The fonts worked with powerline on linux for me as well, however not on Mac. I have found a solution using Nerd Fonts with Mac OS.
